# Numpy Assignment

### Q-1. Numpy’da Vektor ve Matrisin farkini tek cumle ile ifade ediniz.

In [1]:
#Vector is a one-dimensional array. Matrices are multi-dimentional arrays.

### Q-2. 10 elemanli bir listeden NumPy Array’i olusturunuz.

In [2]:
import numpy as np
a = [1, 3, 5, 6, 7, 8, 9, 11, 13, 15]
b = np.array(a)
b

array([ 1,  3,  5,  6,  7,  8,  9, 11, 13, 15])

### Q-3. Icerisinde ‘0’ lar olan, ve veri tipi integer olan 10X10’luk bir matris olusturunuz.

In [3]:
np.zeros((10, 10), dtype = 'int32')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

### Q-4. Icerisinde ‘1’ ler olan, veri tipi float olan 10X10’luk bir matris olusturunuz.

In [4]:
np.ones((10, 10), dtype = 'float32')

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)

### Q-5. Icerisinde ‘9’ lar olan, veri tipi integer olan 10X10’luk bir matris olusturunuz.

In [5]:
a = np.full((10, 10),9)
a

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [6]:
a.dtype

dtype('int32')

### Q-6. 5 ile 25 arasinda, 3’er 3’er atlayan tek boyutlu bir Array olusturunuz.

In [7]:
np.arange(5, 25, 3)

array([ 5,  8, 11, 14, 17, 20, 23])

### Q-7. -1 ile 1 arasinda 30 adet Array olusturunuz.
#### Student note: Sanirim 30 elemanli array demek istendi. Aksi takdirde arrayin uzunlugu bilgisi eksik kalmis olacak.

In [8]:
np.linspace(-1, 1, 30)

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

### Q-8. 0 ile 30 arasinda 5x6’lik bir matris olusturun.

In [9]:
np.random.randint(0, 30, (5, 6))

array([[25, 23,  6,  7, 29, 14],
       [12, 19, 23, 25, 20,  1],
       [24, 12,  7, 19, 28, 12],
       [14,  1, 22, 23, 12, 22],
       [22,  4, 19, 27, 26, 13]])

### Q-9. Kosegenleri 1 olan 10x10’luk bir matris olusturunuz. 

In [10]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

### Q-10. 0 ile 10 arasinda 5x10’lik bir matris olusturun. (integer) ve bu matrisin;
#### a. eleman sayisini
#### b. boyut bilgisini/sayisini
#### c. satir X sutun bilgisini
#### d.veri tipini numpy metodlariyla yazdiriniz.

In [11]:
a = np.random.randint(0, 10, (5, 10))
a

array([[8, 9, 7, 8, 2, 8, 0, 1, 3, 5],
       [2, 0, 9, 6, 9, 9, 1, 3, 1, 7],
       [7, 2, 2, 3, 6, 9, 1, 1, 5, 0],
       [3, 7, 6, 6, 9, 5, 9, 4, 5, 8],
       [7, 7, 4, 7, 5, 9, 6, 3, 9, 2]])

In [12]:
a.size

50

In [13]:
a.ndim

2

In [14]:
a.shape

(5, 10)

In [15]:
a.dtype

dtype('int32')

### Q-11. 0 ile 10 arasindaki degerlerden olusan 3 adet 4x7’lik bir matris olusturunuz. (3 boyutlu bir matris olusturulacak) 

In [16]:
np.random.randint(0, 10, size = (3, 4, 7))

array([[[3, 0, 5, 4, 1, 1, 2],
        [3, 4, 8, 2, 6, 8, 6],
        [1, 1, 6, 9, 7, 4, 0],
        [4, 8, 4, 7, 7, 5, 1]],

       [[7, 5, 3, 0, 4, 6, 6],
        [9, 5, 3, 3, 1, 5, 7],
        [6, 7, 4, 1, 1, 8, 2],
        [5, 7, 3, 5, 8, 1, 2]],

       [[7, 4, 1, 3, 3, 8, 2],
        [1, 6, 7, 4, 1, 1, 3],
        [3, 5, 6, 0, 4, 6, 7],
        [2, 0, 2, 9, 1, 9, 4]]])

### Q-12. Bir vektor olusturunuz ve daha sonrasinda ayni vektoru bir matrise ceviriniz. (boyut sayisini degistirin.)

In [17]:
vector = np.arange(0, 6)
vector

array([0, 1, 2, 3, 4, 5])

In [18]:
matrix = vector.reshape(2, 3)
matrix

array([[0, 1, 2],
       [3, 4, 5]])

### Q-13. 4 tane ayri tek boyutlu array’i birlestirerek bir array olusturunuz.

In [19]:
a = np.array([1])
b = np.array([2, 3])
c = np.array([4, 5, 6])
d = np.array([7, 8, 9, 10])
e = np.concatenate([a, b, c, d])
e

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Q-14. 2 boyutlu bir vektor ve bir matris olusturun(ayri ayri), bu iki arrayi numpy metodlarini kullanarak sutun bazli birlestiriniz.

In [20]:
a = np.random.randint(10, size = (2,3))
a

array([[8, 5, 4],
       [4, 2, 6]])

In [21]:
b = np.random.randint(10, size = (2, 1))
b

array([[9],
       [3]])

In [22]:
np.concatenate([a, b], axis = 1)

array([[8, 5, 4, 9],
       [4, 2, 6, 3]])

### Q-15. Numpy’da “axis=1” ve “axis=0”  arasinda ne fark vardir. Teorik olarak yaziniz?  

In [23]:
# axis=0 is for concatenating arrays according to their verticals
# axis=1 is for concatenating arrays according to their horizontals

### Q-16. Farkli boyutlardaki arraylari satin ve sutun bazli ayri ayri birlestiriniz.

In [24]:
a = np.random.randint(10, size = (2, 4))
b = np.random.randint(10, size = (3, 4))
a, b

(array([[1, 2, 0, 4],
        [5, 6, 7, 4]]),
 array([[2, 3, 1, 0],
        [4, 4, 4, 5],
        [2, 1, 2, 8]]))

In [25]:
np.vstack([a, b])

array([[1, 2, 0, 4],
       [5, 6, 7, 4],
       [2, 3, 1, 0],
       [4, 4, 4, 5],
       [2, 1, 2, 8]])

In [26]:
a = np.random.randint(10, size = (3, 5))
b = np.random.randint(10, size = (3, 2))
a, b

(array([[8, 5, 0, 4, 5],
        [2, 9, 5, 5, 6],
        [5, 1, 2, 7, 6]]),
 array([[2, 4],
        [5, 0],
        [2, 4]]))

In [27]:
np.hstack([a, b])

array([[8, 5, 0, 4, 5, 2, 4],
       [2, 9, 5, 5, 6, 5, 0],
       [5, 1, 2, 7, 6, 2, 4]])

### Q-17. 10 elemanli bi liste olusturunuz ve bu listeyi Numpy metodlariyla bolerek(split) 4 ayri array olusturunuz.

In [28]:
a = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
np.split(a, [3, 5, 8])

[array([0, 1, 2]), array([3, 4]), array([5, 6, 7]), array([8, 9])]

### Q-18. Random bir array olusturunuz ve bu arrayi buyukten kucuge dogru siralayiniz.Ve bu siralamadan sonra hangi elemanin hangi indexte oldugunu gosteren bir metod uygulayiniz.

In [29]:
a = np.random.randint(0,20, 10)
a

array([ 7,  9, 19,  3, 19,  6, 12, 13,  0,  3])

In [30]:
b = np.sort(a)
b[::-1]

array([19, 19, 13, 12,  9,  7,  6,  3,  3,  0])

### Q-19. 20 elemanli random bir vektor olusturunuz. Bu vektorun 3. 5. ve 7. elemanlarina ulasin.

In [31]:
a = np.random.randint(0, 20, 20)
a

array([ 1,  4, 11, 12,  6, 13,  5, 15, 17,  4, 16,  8, 17, 16, 18,  9,  1,
        1, 11,  8])

In [32]:
[a[3], a[5], a[7]]

[12, 13, 15]

### Q-20. 10 elemanli random bir vektor olusturunuz ve bu arrayin  4. elemanini farkli bir sayiyla degistiriniz.

In [33]:
a = np.random.randint(0, 20, 10)
a

array([ 5,  5, 13,  5,  9,  8, 13,  7, 16,  6])

In [34]:
a[4] = 2222
a

array([   5,    5,   13,    5, 2222,    8,   13,    7,   16,    6])

### Q-21. “Diagonal Matrix” ve “Trace Matrix”  kavramlari hakkinda kucuk bir arastirma yapip bunlarin ne oldugunu belirten kucuk bir aciklama yaziniz.

In [35]:
# A diagonal matrix is a matrix in which the entries outside the main diagonal are all zero.
# The trace of a matrix is defined to be the sum of elements on the main diagonal. Only for square matrices.aa

### Q-22. 5x5’lik Diagonal bir matris olusturunuz ve Diagonaline denk gelen indexlere ulasiniz.(ayri ayri)

In [36]:
a = np.random.randint(20, size = (5, 5))
a

array([[10,  5, 10, 14,  0],
       [ 4, 14,  0, 16, 15],
       [17, 10,  4,  3, 19],
       [18,  3, 18, 15,  3],
       [ 8, 13, 19, 14, 19]])

In [37]:
a[0,0], a[1,1], a[2,2], a[3,3], a[4,4]

(10, 14, 4, 15, 19)

### Q-23. 10 ile 20 arasinda bir vektor olusturunuz. Ve 3. indexten son indexe kadar olan degerleri yazdiriniz.

In [38]:
a = np.arange(10, 20)
a[3:]

array([13, 14, 15, 16, 17, 18, 19])

### Q-24. 10X10 luk bir matris olusturunuz ve ;
#### a. 3.satir ve 5.sutuna ulasiniz.
#### b. 5.sutunun tum satirlarina ulasiniz.
#### c. Tum sutunlarin 2.satirlarina ulasiniz.
#### d. tum sutunlarin 2 ile 7 arasindaki satirlarina ulasiniz.
#### e. satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerlere ulasiniz.
#### f. satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerlere ulasiniz.
#### g. sutun indexi sadece 3, 6,9 olan kolonlarin(sutunlarin), tum satirlarina ulasiniz.
#### h. 5. indexli satir ve 5.indexli sutuna denk gelen degeri, dogum yilinizla degistiriniz. 

In [39]:
a = np.random.randint(0, 100, (10, 10))
a

array([[98, 48, 98, 95, 35, 55, 77, 24, 71, 19],
       [30,  7, 96, 71, 43, 38,  5, 27, 16, 47],
       [21,  3, 75,  4, 22, 78, 31, 44, 88, 64],
       [ 1, 29, 59, 59, 45, 94, 43, 81,  0, 97],
       [97, 20, 74, 56, 41, 43, 73, 83, 78, 65],
       [53, 89,  9, 54, 89, 64, 64, 42, 23, 89],
       [10,  3, 19,  1, 96, 43, 61, 48, 81, 81],
       [74,  1, 73, 41, 14, 95, 73, 61, 32, 57],
       [20, 89, 53, 89, 27, 87, 36, 50, 47, 45],
       [41, 98, 67, 32, 39, 38, 83,  8, 20, 65]])

In [40]:
a[3,5]

94

In [41]:
a[:, 5]

array([55, 38, 78, 94, 43, 64, 43, 95, 87, 38])

In [42]:
a[2, :]

array([21,  3, 75,  4, 22, 78, 31, 44, 88, 64])

In [43]:
a[2:7,:]

array([[21,  3, 75,  4, 22, 78, 31, 44, 88, 64],
       [ 1, 29, 59, 59, 45, 94, 43, 81,  0, 97],
       [97, 20, 74, 56, 41, 43, 73, 83, 78, 65],
       [53, 89,  9, 54, 89, 64, 64, 42, 23, 89],
       [10,  3, 19,  1, 96, 43, 61, 48, 81, 81]])

In [44]:
a[2:5, 3:7]

array([[ 4, 22, 78, 31],
       [59, 45, 94, 43],
       [56, 41, 43, 73]])

In [45]:
a[5:,:4]

array([[53, 89,  9, 54],
       [10,  3, 19,  1],
       [74,  1, 73, 41],
       [20, 89, 53, 89],
       [41, 98, 67, 32]])

In [46]:
[a[:,3],a[:,6],a[:,9]]

[array([95, 71,  4, 59, 56, 54,  1, 41, 89, 32]),
 array([77,  5, 31, 43, 73, 64, 61, 73, 36, 83]),
 array([19, 47, 64, 97, 65, 89, 81, 57, 45, 65])]

In [47]:
a[5,5] = 1987
a

array([[  98,   48,   98,   95,   35,   55,   77,   24,   71,   19],
       [  30,    7,   96,   71,   43,   38,    5,   27,   16,   47],
       [  21,    3,   75,    4,   22,   78,   31,   44,   88,   64],
       [   1,   29,   59,   59,   45,   94,   43,   81,    0,   97],
       [  97,   20,   74,   56,   41,   43,   73,   83,   78,   65],
       [  53,   89,    9,   54,   89, 1987,   64,   42,   23,   89],
       [  10,    3,   19,    1,   96,   43,   61,   48,   81,   81],
       [  74,    1,   73,   41,   14,   95,   73,   61,   32,   57],
       [  20,   89,   53,   89,   27,   87,   36,   50,   47,   45],
       [  41,   98,   67,   32,   39,   38,   83,    8,   20,   65]])

### Q-25. 0’dan 50’ye kadar 5’er 5’er atlayarak giden bir array olusturunuz(tek boyutlu) ve numpy metodlariyla asagidaki islemleri uygulayin;
#### a. 20 den buyuk olan kac deger var.
#### b. 30’dan kucuk kac deger var
#### c. icerisinde 33 gecen kac deger var
#### d. olusturulan arrayin tum elemanlarini 5 ile carpin.
#### e. olusturulan arrayin tum elemanlarinin 2 ile bolumunden kalanlari yazdiriniz.

In [48]:
a = np.arange(0, 50, 5)
a

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [49]:
np.sum(a>20)

5

In [50]:
np.sum(a<30)

6

In [51]:
np.sum(a==33)

0

In [52]:
np.multiply(5, a)

array([  0,  25,  50,  75, 100, 125, 150, 175, 200, 225])

In [53]:
np.array(a%2)

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

### Q-26. 0 ile 1 arasinda 50 elamanli bir array olusturunuz ve;
#### a. ortalamasini aliniz.
#### b. standart sapmasini aliniz.
#### c. varyansini aliniz.
#### d. median’ini aliniz.
#### e. en kucuk degeri bulunuz.
#### f. en buyuk degeri bulunuz.

In [54]:
a = np.random.random((1,50))
a

array([[0.42364041, 0.14001046, 0.48404206, 0.10264366, 0.85236965,
        0.21533182, 0.06179647, 0.2191565 , 0.27654079, 0.41609414,
        0.62847603, 0.17231479, 0.24626757, 0.08826052, 0.19149012,
        0.11638251, 0.72291145, 0.7113106 , 0.43469507, 0.9100565 ,
        0.70896851, 0.15940669, 0.75732207, 0.70062733, 0.30962484,
        0.43825524, 0.93137205, 0.09052457, 0.8529573 , 0.50077457,
        0.0442887 , 0.9471753 , 0.12117447, 0.42205207, 0.80622446,
        0.08859906, 0.79346437, 0.22127982, 0.55652178, 0.80814889,
        0.90626308, 0.93845757, 0.22245324, 0.84627899, 0.32807446,
        0.68633038, 0.93396138, 0.52466983, 0.38443794, 0.07426716]])

In [55]:
np.mean(a)

0.47035494424470625

In [56]:
np.std(a)

0.30061140993792546

In [57]:
np.var(a)

0.09036721978486746

In [58]:
np.median(a)

0.4291677432851905

In [59]:
np.min(a)

0.04428870124295359

In [60]:
np.max(a)

0.9471752982660046